name: Linux unit tests and system tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linux-build-and-test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: debug
        run: |
          env -0 | while IFS='' read -d '' line ; do printf '%s\t: %s\n' "${line%%=*}" "${line#*=}" | expand -t 30 | sed ':a;N;$!ba;s/\n/ /g'; done | LC_COLLATE=C sort -b

      - uses: actions/checkout@v4
        with:
          # Needed to fetch the tags for versioningit
          fetch-depth: "0"
      
      - name: Run unit tests and system tests on Linux
        run: ${GITHUB_WORKSPACE}/buildconfig/Jenkins/Conda/conda-buildscript ${GITHUB_WORKSPACE} linux-64-ci --enable-systemtests

      - name: Upload build and test log artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: |
            ${{ github.workspace }}/build/test_logs/*.log
            ${{ github.workspace }}/build/**/*-mismatch.nxs

      - name: Unit Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Linux Unit Tests
          path: build/Testing/*unittest.xml
          reporter: java-junit
          fail-on-error: false

      - name: System Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Linux System Tests
          path: build/Testing/SystemTests/**/TEST-systemtests*.xml
          reporter: java-junit
          fail-on-error: false

